[versions]
agp = "8.13.2"
kotlin = "2.2.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"
googleGmsGoogleServices = "4.4.4"
firebaseFirestore = "26.0.2"
firebaseAuth = "24.0.1"
firebaseStorage = "22.0.1"
nav = "2.7.3"
navigationFragmentKtx = "2.9.6"
navigationUiKtx = "2.9.6"

[libraries]
androidx_core_ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx_junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx_espresso_core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx_appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx_activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx_constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase_firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase_auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase_storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
androidx_navigation_fragment_ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "nav" }
androidx_navigation_ui_ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "nav" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.9.0" }
retrofit_gson = { group = "com.squareup.retrofit2", name = "converter-gson", version = "2.9.0" }
okhttp_logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version = "4.11.0" }
google_auth = { group = "com.google.auth", name = "google-auth-library-oauth2-http", version = "1.23.0" }


[plugins]
android_application = { id = "com.android.application", version.ref = "agp" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google_gms_google_services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
androidx_navigation_safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "nav" }

